
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: postgres
  password: 1234

development:
  <<: *default
  database: shopping_cart

test:
  <<: *default
  database: shopping_cart_test

production:
  <<: *default
  database: shopping_cart_production
